### ISSUE TITLE
Set up some standard datasets

### ISSUE THREAD

**Issue by dabasajay** [IOSD/learn-em-all#1]
Make a folder named datasets and write code for these standard datasets:
- [IRIS Dataset](https://archive.ics.uci.edu/ml/datasets/iris)
- [Diabetes Dataset](https://scikit-learn.org/stable/datasets/index.html#diabetes-dataset)

These datasets should be easily importable
For example:

```python
from learnemall.datasets import diabetes
# Returns numpy arrays
X, y = diabetes.load_data()
print(X.shape)
print(y.shape)
```

For any doubt or suggestion, comment below

**Comment by JARVVVIS** [comment]
Ruchit (Team-A), I want to claim this issue.

**Comment by HardikJ7321** [comment]
Hardik ( TEAM-C ) , I would like to claim this issue.

**Comment by srishtisrivastava014** [comment]
I would like to claim to this issue -Srishti team B

**Comment by Ayush789** [comment]
> Hardik ( TEAM-C ) , I would like to claim this issue.

Claim Awarded
