### ISSUE TITLE
Implement Standard Scaling

### ISSUE THREAD

**Issue by Ayush789** [IOSD/learn-em-all#2]
Implement Standard Scaling
It should be of the format:
`ss = learnemall.StandardScaler()`
`x = ss.Scale(x)`

it should take a numpy array as input and produce a numpy array where each element is
**z = (x - u) / s**
where x is the original element, u is the mean of the column, s is the std deviation and z is the new element.

**Comment by Ayush789** [comment]
Here StandardScaler is a class with two functions Scale and Revert. 
Revert should replace each element with
**z = x*s + u**
where s is the original std deviation of the column, u is the original mean of the column, x is the original element and z is the new element

**Comment by dabasajay** [comment]
> Here StandardScaler is a class with two functions Scale and Revert.
Just a small suggestion: Since Scale and Revert are class methods so just for the sake of convention, name them in lowercase(`.scale()` & `.revert()`) and the class name `StandardScaler` in uppercase.

**Comment by eKuG** [comment]
Ekansh Gupta (Team B) - I would like to claim this issue

**Comment by Ayush789** [comment]
> Ekansh Gupta (Team B) - I would like to claim this issue

Claim Awarded
