### ISSUE TITLE
Implement MinMax Scaler

### ISSUE THREAD

**Issue by Ayush789** [IOSD/learn-em-all#3]
Implement MinMax Scaling
It should be of the format:
`mms = learnemall.MinMaxScale()`
`x = mms.Scale(x)`

it should take a numpy array as input and produce a numpy array where each element is
**z = (x - min) / (max - min)**
where x is the original element, min is the smallest element of the column, max is the largest element of the column and z is the new element.

**Comment by Ayush789** [comment]
Here MinMaxScaler is a class with two functions Scale and Revert.
Revert should replace each element with
**z = x * (max-min) + min**
where min is the smallest element of the original column, max is the largest element of the original column, x is the original element and z is the new element

**Comment by dabasajay** [comment]
> Here MinMaxScaler is a class with two functions Scale and Revert.

Just a small suggestion: Since `Scale` and `Revert` are class methods so just for the sake of convention, name them in lowercase(`.scale()` & `.revert()`) and the class name `MinMaxScaler` in uppercase.

**Comment by JARVVVIS** [comment]
Ruchit (Team-A), I would like to claim this issue

**Comment by HardikJ7321** [comment]
Hardik (TEAM -C ) , I would like to claim this issue

**Comment by Ayush789** [comment]
> Ruchit (Team-A), I would like to claim this issue

Claim Awarded
