### ISSUE TITLE
Implement Linear Regression Class

### ISSUE THREAD

**Issue by dabasajay** [IOSD/learn-em-all#7]
`LinearRegression` class should have these methods:
- `.fit(X,y)` :- it takes in features(X) and targets(y) and trains the model.
- `.predict(X)` :- it takes features(X) as input and outputs the predictions.

Test your model on Diabetes dataset available in the library and check how well it performs.
Example code

```python
import numpy as np
from learnemall.datasets import diabetes
from learnemall.linear import LinearRegression
model = LinearRegression()
X,y = diabetes.load_dataset()
# train the model
model.fit(X,y)
# predict using model
y_pred = model.predict(X)
# Evaluate
print("Mean squared error: {}".format(np.square(y_pred-y).mean()))
```

**Comment by eKuG** [comment]
Would like to claim the issue!

**Comment by Ayush789** [comment]
> Would like to claim the issue!

Claim Awarded
